### get-test
GET http://localhost:3000/api/test/get-test
Content-Type: application/json

### post-test
POST http://localhost:3000/api/test/post-test
Content-Type: application/json

{
    "id" : 1,
    "name" : "なまえ"
}

### database-test
GET http://localhost:3000/api/test/database-test
Content-Type: application/json